version: '3'
services:
  master:
    image: "nhoss2/pymada-master"
    ports:
      - "30200:8000"
    command: make setup-test-server
    environment:
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: "DEBUG"
  
  agent1:
    image: "nhoss2/pymada-node-puppeteer"
    command: 'gunicorn "wsgi:app" -b 0.0.0.0:5001'
    depends_on:
      - master
    ports:
      - "5001:5001"
    environment:
      AGENT_ADDR: "agent1"
      MASTER_URL: "http://master:8000"
      AGENT_PORT: "5001"
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: "DEBUG"
  
  agent2:
    image: "nhoss2/pymada-node-puppeteer"
    command: 'gunicorn "wsgi:app" -b 0.0.0.0:5001'
    depends_on:
      - master
    ports:
      - "5002:5001"
    environment:
      AGENT_ADDR: "agent2"
      MASTER_URL: "http://master:8000"
      AGENT_PORT: "5001"
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: "DEBUG"