version: '3'
services:
  master:
    image: "pymada/master"
    ports:
      - "30200:8000"
    command: python control.py
    environment:
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: "DEBUG"
      PYMADA_MAX_TASK_DURATION_SECONDS: 180
      #PYMADA_TOKEN_AUTH: "testing"
  
  agent1:
    image: "pymada/selenium-chrome"
    depends_on:
      - master
    ports:
      - "5001:5001"
    environment:
      AGENT_ADDR: "agent1"
      MASTER_URL: "http://master:8000"
      AGENT_PORT: "5001"
      PYTHONUNBUFFERED: 1
      LOG_LEVEL: "DEBUG"
      #PYMADA_TOKEN_AUTH: "testing"
    shm_size: "2gb"

#  agent2:
#    image: "pymada/node-puppeteer"
#    command: 'gunicorn "wsgi:app" -b 0.0.0.0:5001'
#    depends_on:
#      - master
#    ports:
#      - "5002:5001"
#    environment:
#      AGENT_ADDR: "agent2"
#      MASTER_URL: "http://master:8000"
#      AGENT_PORT: "5001"
#      PYTHONUNBUFFERED: 1
#      LOG_LEVEL: "DEBUG"
#      #PYMADA_TOKEN_AUTH: "testing"
