# Generated by Django 2.2.3 on 2019-08-26 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.TextField()),
                ('agent_state', models.CharField(choices=[('IDLE', 'IDLE'), ('RUNNING', 'RUNNING'), ('ASSIGNED', 'ASSIGNED'), ('LOST', 'LOST'), ('NO_RUNNER', 'NO_RUNNER')], default='NO_RUNNER', max_length=10)),
                ('last_contact', models.IntegerField()),
                ('agent_url', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contents', models.TextField()),
                ('file_name', models.CharField(max_length=200)),
                ('file_type', models.CharField(max_length=200)),
                ('custom_executable', models.CharField(max_length=200, null=True)),
                ('dependency_file', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UrlTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('json_metadata', models.TextField(null=True)),
                ('task_result', models.TextField(null=True)),
                ('task_state', models.CharField(choices=[('QUEUED', 'QUEUED'), ('ASSIGNED', 'ASSIGNED'), ('COMPLETE', 'COMPLETE')], default='QUEUED', max_length=10)),
                ('fail_num', models.IntegerField(default=0)),
                ('start_time', models.FloatField(default=0)),
                ('assigned_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_server.Agent')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reporting_agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_server.Agent')),
                ('runner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_server.Runner')),
            ],
        ),
        migrations.AddField(
            model_name='agent',
            name='assigned_runner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_server.Runner'),
        ),
    ]
