# Generated by Django 2.2.5 on 2019-09-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_server', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='assigned_runner',
        ),
        migrations.AddField(
            model_name='agent',
            name='runner_num',
            field=models.IntegerField(null=True),
        ),
    ]
