# Generated by Django 2.2.5 on 2019-10-15 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master_server', '0002_auto_20190930_0535'),
    ]

    operations = [
        migrations.AddField(
            model_name='urltask',
            name='screenshot',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
