# Generated by Django 2.2.5 on 2019-11-06 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master_server', '0003_urltask_screenshot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='urltask',
            name='screenshot',
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('screenshot', models.ImageField(upload_to='')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='master_server.UrlTask')),
            ],
        ),
    ]
