# Generated by Django 2.2.5 on 2020-01-03 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_server', '0005_urltask_end_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='last_contact',
            new_name='last_contact_attempt',
        ),
    ]
