puppeteer:
	docker build -f puppeteer.dockerfile .. -t nhoss2/pymada-node-puppeteer

selenium-firefox:
	docker build -f selenium-firefox.dockerfile .. -t nhoss2/pymada-selenium-firefox

selenium-chrome:
	docker build -f selenium-chrome.dockerfile .. -t nhoss2/pymada-selenium-chrome

.PHONY: puppeteer selenium-firefox selenium-chrome
