provision:
    provider:
        name: digital_ocean
        token:
    instance:
        size: s-1vcpu-1gb
        image: 18.04.3 (LTS) x64

pymada:
    max_task_duration_seconds: 300
    max_task_retries: 3
    no_agents_on_master_node: true
    agent_pod_limits:
        cpu: 0.9
        memory: 1000Mi