provision:
    provider:
        name: google_cloud
        user: compute@something.gserviceaccount.com
        auth_file: computeauth.json
        project: project_name
        preempt_master: false
        preempt_agents: true
    instance:
        size: g1-small
        image: ubuntu-1804

pymada:
    max_task_duration_seconds: 300
    max_task_retries: 3
    no_agent_on_master_node: true
    agent_pod_limits:
        cpu: 0.9
        memory: 1000Mi