apiVersion: v1
kind: Service
metadata:
  name: pymadamaster
  labels:
    service: pymada-master-service
spec:
  selector:
    app: pymada-master
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000