apiVersion: v1
kind: Service
metadata:  
  name: pymada-master-nodeport
  labels:
    service: pymada-master-nodeport
spec:
  selector:    
    app: pymada-master
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    nodePort: 30200
    protocol: TCP